#pragma once

#define PGS_FRAGMENT_SHADER_NAME "../src/shader.frag"
#define PGS_SHADER_FILE_SIZE 8000
#define PGS_START_WINDOW_WIDTH 1280
#define PGS_START_WINDOW_HEIGHT 720
#define PGS_MAX_VERT 256
#define PGS_MAX_FACE 32
#define PGS_MAX_SPHERE 16
#define PGS_EPSILON 0.001
